fix Hardware Serial for esp32
mandulaj/PZEM-004T-v30 pull request #31
Opened 2020-07-14 05:55 UTC by nguyenhuudamy

2020-07-28 19:57 UTC, mandulaj commented
Hi @nguyenhuudamy Thanks for the PR. However I don't like the idea of changing an established API. It would for sure break my projects not to mention anyone who already uses this library... Perhaps we can overload the function or wrap it in a #if #else to fix it just for the esp32 platform while retaining the Arduino compatible API.

2021-06-04 14:39 UTC, ManuelJimenezBuendia commented
What about something like this?
**.h**
#ifdef ESP32
	PZEM004Tv30(HardwareSerial* port, int rx_pin, int tx_pin, uint8_t addr=PZEM_DEFAULT_ADDR);
#endif

**.cpp**
#ifdef ESP32
  PZEM004Tv30::PZEM004Tv30(HardwareSerial* port, int rx_pin, int tx_pin, uint8_t addr)
  {
    port->begin(PZEM_BAUD_RATE, SERIAL_8N1, rx_pin, tx_pin);  //Baud rate, parity mode, RX, TX
    this->_serial = port;
    this->_isSoft = false;
    init(addr);
  }
 #endif

2021-06-04 14:41 UTC, ManuelJimenezBuendia commented on PZEM004Tv30.h
> +    PZEM004Tv30(HardwareSerial* port, uint8_t receivePin, uint8_t transmitPin, uint8_t addr=PZEM_DEFAULT_ADDR);
Add #ifdef ESP32 ..... #endif fro ESP32? And don't remove previous constructor

2021-07-15 09:07 UTC, mandulaj requested changes
So I added the requested `#if def` and modified the examples in order to be compatible. It has compiled however I have no way of testing it on any board at the moment. Could anyone with access to an ESP32 board try this? Maybe @ASMotionLab if you have time.

2021-07-15 09:19 UTC, ASMotionLab commented
Thanks @mandulaj, looks great at a glance - I will check it out this evening, test with my ESP32 and report 👍

2021-07-15 11:33 UTC, mandulaj commented
I managed to get hold of an ESP32 and it seems to work fine... So I am ready to merge right away.

2021-07-15 11:35 UTC, mandulaj approved these changes
I added the ESP32 switch and it works fine now

2021-07-15 11:37 UTC, merged